//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduledTask.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumName() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScheduledTask.Properties.EnumName", typeof(EnumName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 系统权限 的本地化字符串。
        /// </summary>
        internal static string AuthorityPriorityEnum_Core {
            get {
                return ResourceManager.GetString("AuthorityPriorityEnum_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑权限 的本地化字符串。
        /// </summary>
        internal static string AuthorityPriorityEnum_Logic {
            get {
                return ResourceManager.GetString("AuthorityPriorityEnum_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布数据错误 的本地化字符串。
        /// </summary>
        internal static string EmailLogCategoryEnum_DataSyncError {
            get {
                return ResourceManager.GetString("EmailLogCategoryEnum_DataSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布通知错误 的本地化字符串。
        /// </summary>
        internal static string EmailLogCategoryEnum_InformChangeError {
            get {
                return ResourceManager.GetString("EmailLogCategoryEnum_InformChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态属性结构变更 的本地化字符串。
        /// </summary>
        internal static string EmailLogCategoryEnum_PropertyStructChange {
            get {
                return ResourceManager.GetString("EmailLogCategoryEnum_PropertyStructChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他业务线 的本地化字符串。
        /// </summary>
        internal static string EmailReceiverCompanyEnum_Other {
            get {
                return ResourceManager.GetString("EmailReceiverCompanyEnum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淘车 的本地化字符串。
        /// </summary>
        internal static string EmailReceiverCompanyEnum_Taoche {
            get {
                return ResourceManager.GetString("EmailReceiverCompanyEnum_Taoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易车 的本地化字符串。
        /// </summary>
        internal static string EmailReceiverCompanyEnum_Yiche {
            get {
                return ResourceManager.GetString("EmailReceiverCompanyEnum_Yiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易湃 的本地化字符串。
        /// </summary>
        internal static string EmailReceiverCompanyEnum_Yipai {
            get {
                return ResourceManager.GetString("EmailReceiverCompanyEnum_Yipai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 make 的本地化字符串。
        /// </summary>
        internal static string FilterEnum_Make {
            get {
                return ResourceManager.GetString("FilterEnum_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 manufacturer 的本地化字符串。
        /// </summary>
        internal static string FilterEnum_Manufacturer {
            get {
                return ResourceManager.GetString("FilterEnum_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 masterBrand 的本地化字符串。
        /// </summary>
        internal static string FilterEnum_MasterBrand {
            get {
                return ResourceManager.GetString("FilterEnum_MasterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 model 的本地化字符串。
        /// </summary>
        internal static string FilterEnum_Model {
            get {
                return ResourceManager.GetString("FilterEnum_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 style 的本地化字符串。
        /// </summary>
        internal static string FilterEnum_Style {
            get {
                return ResourceManager.GetString("FilterEnum_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 year 的本地化字符串。
        /// </summary>
        internal static string FilterEnum_Year {
            get {
                return ResourceManager.GetString("FilterEnum_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        internal static string ImportantLevelEnum_General {
            get {
                return ResourceManager.GetString("ImportantLevelEnum_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重要 的本地化字符串。
        /// </summary>
        internal static string ImportantLevelEnum_Important {
            get {
                return ResourceManager.GetString("ImportantLevelEnum_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string ImportantLevelEnum_Other {
            get {
                return ResourceManager.GetString("ImportantLevelEnum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PV_1-100 的本地化字符串。
        /// </summary>
        internal static string LevelEnum_Level1 {
            get {
                return ResourceManager.GetString("LevelEnum_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PV_101-200 的本地化字符串。
        /// </summary>
        internal static string LevelEnum_Level2 {
            get {
                return ResourceManager.GetString("LevelEnum_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PV_201-300 的本地化字符串。
        /// </summary>
        internal static string LevelEnum_Level3 {
            get {
                return ResourceManager.GetString("LevelEnum_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PV_301-400 的本地化字符串。
        /// </summary>
        internal static string LevelEnum_Level4 {
            get {
                return ResourceManager.GetString("LevelEnum_Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PV_401-500 的本地化字符串。
        /// </summary>
        internal static string LevelEnum_Level5 {
            get {
                return ResourceManager.GetString("LevelEnum_Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PV_500以后 的本地化字符串。
        /// </summary>
        internal static string LevelEnum_Level6 {
            get {
                return ResourceManager.GetString("LevelEnum_Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专用车 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Cross {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两厢轿车 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Hatchback {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Hatchback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Micro-Bus厢式车 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Micro {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mpv 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Mpv {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Mpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Other {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick-up皮卡 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Pickup {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三厢轿车 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Sedans {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Sedans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跑车 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Sports {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suv 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Suv {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Suv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wagon旅行车 的本地化字符串。
        /// </summary>
        internal static string ModelBodyFormEnum_Wagon {
            get {
                return ResourceManager.GetString("ModelBodyFormEnum_Wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Bus {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧凑型车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Compact {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 概念车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Concept {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重卡 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_HeavyTruck {
            get {
                return ResourceManager.GetString("ModelLevelEnum_HeavyTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻客 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_LightBus {
            get {
                return ResourceManager.GetString("ModelLevelEnum_LightBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻卡 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_LightTruck {
            get {
                return ResourceManager.GetString("ModelLevelEnum_LightTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 豪华车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Luxury {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Luxury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中大型车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_MediumLarge {
            get {
                return ResourceManager.GetString("ModelLevelEnum_MediumLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中型车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Middle {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微型车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Mini {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微卡 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_MiniTruck {
            get {
                return ResourceManager.GetString("ModelLevelEnum_MiniTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mpv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Mpv {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Mpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Other {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮卡 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Pickup {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小型车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Small {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跑车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Sports {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Suv {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Suv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面包车 的本地化字符串。
        /// </summary>
        internal static string ModelLevelEnum_Van {
            get {
                return ResourceManager.GetString("ModelLevelEnum_Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string ModelLevelSecondEnum_Other {
            get {
                return ResourceManager.GetString("ModelLevelSecondEnum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧凑型Suv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelSecondEnum_SuvCompact {
            get {
                return ResourceManager.GetString("ModelLevelSecondEnum_SuvCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型Suv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelSecondEnum_SuvFullSize {
            get {
                return ResourceManager.GetString("ModelLevelSecondEnum_SuvFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中大型Suv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelSecondEnum_SuvLarge {
            get {
                return ResourceManager.GetString("ModelLevelSecondEnum_SuvLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中型Suv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelSecondEnum_SuvMedium {
            get {
                return ResourceManager.GetString("ModelLevelSecondEnum_SuvMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小型Suv 的本地化字符串。
        /// </summary>
        internal static string ModelLevelSecondEnum_SuvSmall {
            get {
                return ResourceManager.GetString("ModelLevelSecondEnum_SuvSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在产 的本地化字符串。
        /// </summary>
        internal static string ProductionStatusEnum_InProduction {
            get {
                return ResourceManager.GetString("ProductionStatusEnum_InProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停产 的本地化字符串。
        /// </summary>
        internal static string ProductionStatusEnum_StopProduction {
            get {
                return ResourceManager.GetString("ProductionStatusEnum_StopProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待查 的本地化字符串。
        /// </summary>
        internal static string ProductionStatusEnum_ToBeCheched {
            get {
                return ResourceManager.GetString("ProductionStatusEnum_ToBeCheched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待产 的本地化字符串。
        /// </summary>
        internal static string ProductionStatusEnum_ToBeProduced {
            get {
                return ResourceManager.GetString("ProductionStatusEnum_ToBeProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在销 的本地化字符串。
        /// </summary>
        internal static string SaleStatusEnum_Selling {
            get {
                return ResourceManager.GetString("SaleStatusEnum_Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停销 的本地化字符串。
        /// </summary>
        internal static string SaleStatusEnum_StopSell {
            get {
                return ResourceManager.GetString("SaleStatusEnum_StopSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待查 的本地化字符串。
        /// </summary>
        internal static string SaleStatusEnum_ToBeChecked {
            get {
                return ResourceManager.GetString("SaleStatusEnum_ToBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待销 的本地化字符串。
        /// </summary>
        internal static string SaleStatusEnum_WaitForSale {
            get {
                return ResourceManager.GetString("SaleStatusEnum_WaitForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用 的本地化字符串。
        /// </summary>
        internal static string StatusEnum_Disable {
            get {
                return ResourceManager.GetString("StatusEnum_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string StatusEnum_Enable {
            get {
                return ResourceManager.GetString("StatusEnum_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两厢 的本地化字符串。
        /// </summary>
        internal static string StyleBodyTypeEnum_Hatchback {
            get {
                return ResourceManager.GetString("StyleBodyTypeEnum_Hatchback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两厢半 的本地化字符串。
        /// </summary>
        internal static string StyleBodyTypeEnum_HatchbackHalf {
            get {
                return ResourceManager.GetString("StyleBodyTypeEnum_HatchbackHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮卡 的本地化字符串。
        /// </summary>
        internal static string StyleBodyTypeEnum_Pickup {
            get {
                return ResourceManager.GetString("StyleBodyTypeEnum_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三厢 的本地化字符串。
        /// </summary>
        internal static string StyleBodyTypeEnum_Sedans {
            get {
                return ResourceManager.GetString("StyleBodyTypeEnum_Sedans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单厢 的本地化字符串。
        /// </summary>
        internal static string StyleBodyTypeEnum_Singles {
            get {
                return ResourceManager.GetString("StyleBodyTypeEnum_Singles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待查 的本地化字符串。
        /// </summary>
        internal static string StyleBodyTypeEnum_ToBeChecked {
            get {
                return ResourceManager.GetString("StyleBodyTypeEnum_ToBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商务 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Business {
            get {
                return ResourceManager.GetString("UseEnum_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cross 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Cross {
            get {
                return ResourceManager.GetString("UseEnum_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 家用 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Family {
            get {
                return ResourceManager.GetString("UseEnum_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时尚 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Fashion {
            get {
                return ResourceManager.GetString("UseEnum_Fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多用途 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Mpv {
            get {
                return ResourceManager.GetString("UseEnum_Mpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越野 的本地化字符串。
        /// </summary>
        internal static string UseEnum_OffRoad {
            get {
                return ResourceManager.GetString("UseEnum_OffRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Other {
            get {
                return ResourceManager.GetString("UseEnum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休闲 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Recreation {
            get {
                return ResourceManager.GetString("UseEnum_Recreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代步 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Scooter {
            get {
                return ResourceManager.GetString("UseEnum_Scooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动 的本地化字符串。
        /// </summary>
        internal static string UseEnum_Sport {
            get {
                return ResourceManager.GetString("UseEnum_Sport", resourceCulture);
            }
        }
    }
}
